replicaCount: 1

image:
  repository: maybetuandat/vdt_fe
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30001
  portName: vdt-web-port

# API Backend configuration
backend:
  # Service name của backend trong cluster
  serviceName: "vdt-backend-backend-chart"
  port: 8080

resources: {}
# Health check cho Nginx
healthCheck:
  enabled: true
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}

# Ingress configuration (tùy chọn)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: vdt-web.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Autoscaling (tùy chọn)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80